### ISSUE TITLE
NameError: name 'GL_PROGRAM_POINT_SIZE_EXT' is not defined

### ISSUE THREAD

**Issue by AaronShenny** [TomasBrezina/NeuralNetworkRacing#3] opened 2024-05-26 08:03 UTC
E:\aaronshenny\PROGRAM\NeuralNetworkRacing-master\NeuralNetworkRacing-master>python __main__.py
Traceback (most recent call last):
  File "E:\aaronshenny\PROGRAM\NeuralNetworkRacing-master\NeuralNetworkRacing-master\__main__.py", line 41, in <module>
    app = App(settings)
          ^^^^^^^^^^^^^
  File "E:\aaronshenny\PROGRAM\NeuralNetworkRacing-master\NeuralNetworkRacing-master\app.py", line 67, in __init__
    self.init_gl()
  File "E:\aaronshenny\PROGRAM\NeuralNetworkRacing-master\NeuralNetworkRacing-master\app.py", line 121, in init_gl
    glEnable(GL_PROGRAM_POINT_SIZE_EXT)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'GL_PROGRAM_POINT_SIZE_EXT' is not defined

Can i have a guide to use this?

**Comment by TomasBrezina** [comment] 2024-05-26 10:17
I did not expect for anyone to find this old project after all these years :) Then I found out someone stole my video and put it on Instagram reels.

Anyway the problem was caused by not specified pyglet version.

**Comment by TomasBrezina** [comment] 2024-05-26 10:17
I pushed the fix directly into master.



https://github.com/TomasBrezina/NeuralNetworkRacing/commit/b0170fe950b50e25d7f103b72a61df5768f0bca3

**Closed as completed by TomasBrezina** 2024-05-26 10:17 UTC
